services:
  - type: web
    name: rslang-backend
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.20.4
      - key: MONGO_CONNECTION_STRING
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_REFRESH_SECRET_KEY
        generateValue: true
